export const HOST_API = "http://localhost/dgsm"
export const SESSION_EXPIRED_URL = '/404';
export const OK_STATUS = 200;
export const BAD_REQUEST = 400;
export const UNAUTHORIZED = 401;
export const NOT_FOUND = 404;
export const MEDIA_ERROR_STATUS = 415;
export const VALIDATION_FAILURE_STATUS = 417;
export const DATABASE_ERROR_STATUS = 422;
export const INTERNAL_SERVER_ERROR = 500;






export const TRACK = {

  FETCH_START: 'TRACK_FETCH_START',
  FETCH_SUCCESS: 'TRACK_FETCH_SUCCESS',
  FETCH_ERROR: 'TRACK_FETCH_ERROR',

  FETCH_ALL_START: 'TRACK_FETCH_ALL_START',
  FETCH_ALL_SUCCESS: 'TRACK_FETCH_ALL_SUCCESS',
  FETCH_ALL_ERROR: 'TRACK_FETCH_ALL_ERROR',
  CLEAR_ALL: 'CLEAR_ALL'
}

export const ALBUM = {

  FETCH_START: 'ALBUM_FETCH_START',
  FETCH_SUCCESS: 'ALBUM_FETCH_SUCCESS',
  FETCH_ERROR: 'ALBUM_FETCH_ERROR',

}