// export const HOST_API = "http://localhost/dgsm"
var isLocal = true;
export const HOST_API = !isLocal ? "http://localhost/dgsm" : "https://gogreen-nursery.com/dgsm"
export const SESSION_EXPIRED_URL = '/404';
export const OK_STATUS = 200;
export const BAD_REQUEST = 400;
export const UNAUTHORIZED = 401;
export const NOT_FOUND = 404;
export const MEDIA_ERROR_STATUS = 415;
export const VALIDATION_FAILURE_STATUS = 417;
export const DATABASE_ERROR_STATUS = 422;
export const INTERNAL_SERVER_ERROR = 500;
export const GOOGLE_CLIENT_ID = "770715490238-ft20jtu5vio0krq5c83nih44p48rg715.apps.googleusercontent.com";
export const JWT_SECRET = "amintu";


export const TRACK = {

  FETCH_START: 'TRACK_FETCH_START',
  FETCH_SUCCESS: 'TRACK_FETCH_SUCCESS',
  FETCH_ERROR: 'TRACK_FETCH_ERROR',

  FETCH_ALL_START: 'TRACK_FETCH_ALL_START',
  FETCH_ALL_SUCCESS: 'TRACK_FETCH_ALL_SUCCESS',
  FETCH_ALL_ERROR: 'TRACK_FETCH_ALL_ERROR',
  CLEAR_ALL: 'CLEAR_ALL'
}

export const ALBUM = {

  FETCH_START: 'ALBUM_FETCH_START',
  FETCH_SUCCESS: 'ALBUM_FETCH_SUCCESS',
  FETCH_ERROR: 'ALBUM_FETCH_ERROR',

  DETAIL_FETCH_START: 'ALBUM_DETAIL_FETCH_START',
  DETAIL_FETCH_SUCCESS: 'ALBUM_DETAIL_FETCH_SUCCESS',
  DETAIL_FETCH_ERROR: 'ALBUM_DETAIL_FETCH_ERROR',

  CLEAR_ALL: 'CLEAR_ALL'

}

export const PLAYLIST = {

  FETCH_START: 'PLAYLIST_FETCH_START',
  FETCH_SUCCESS: 'PLAYLIST_FETCH_SUCCESS',
  FETCH_ERROR: 'PLAYLIST_FETCH_ERROR',

  FETCH_TRACKS_START: 'PLAYLIST_TRACKS_FETCH_START',
  FETCH_TRACKS_SUCCESS: 'PLAYLIST_TRACKS_FETCH_SUCCESS',
  FETCH_TRACKS_ERROR: 'PLAYLIST_TRACKS_FETCH_ERROR',

  CREATE_START: 'PLAYLIST_CREATE_START',
  CREATE_SUCCESS: 'PLAYLIST_CREATE_SUCCESS',
  CREATE_ERROR: 'PLAYLIST_CREATE_ERROR',

  ADD_START: 'PLAYLIST_ADD_START',
  ADD_SUCCESS: 'PLAYLIST_ADD_SUCCESS',
  ADD_ERROR: 'PLAYLIST_ADD_ERROR',

  REMOVE_START: 'PLAYLIST_REMOVE_START',
  REMOVE_SUCCESS: 'PLAYLIST_REMOVE_SUCCESS',
  REMOVE_ERROR: 'PLAYLIST_REMOVE_ERROR',

  RENAME_START: 'PLAYLIST_RENAME_START',
  RENAME_SUCCESS: 'PLAYLIST_RENAME_SUCCESS',
  RENAME_ERROR: 'PLAYLIST_RENAME_ERROR',

  REMOVE_TRACK_START: 'PLAYLIST_REMOVE_TRACK_START',
  REMOVE_TRACK_SUCCESS: 'PLAYLIST_REMOVE_TRACK_SUCCESS',
  REMOVE_TRACK_ERROR: 'PLAYLIST_REMOVE_TRACK_ERROR',
}

export const PLAYER = {
  PLAY_PAUSE: 'PLAYER_PLAY_PAUSE',
  MUTE: 'PLAYER_MUTE',
  CURRENT_TIME: 'PLAYER_CURRENT_TIME',
  DURATION_TIME: 'PLAYER_DURATION_TIME',
  CURRENT_TRACK: 'PLAYER_CURRENT_TRACK',
  TRACK_CHANGE: 'PLAYER_TRACK_CHANGE',
  FETCH_PLAY_LIST: 'PLAYER_FETCH_PLAY_LIST',
  ADD_TRACK: 'PLAYER_ADD_TRACK',
  NEXT_TRACK: 'PLAYER_NEXT_TRACK',
  PREV_TRACK: 'PLAYER_PREV_TRACK',
  REMOVE_TRACK: 'PLAYER_REMOVE_TRACK',
  CLEAR_PLAY_LIST: 'PLAYER_CLEAR_PLAY_LIST',
}

export const GLOBAL = {
  CHANGE_THEME: "CHANGE_THEME",
  AUTH_USER_START: "AUTH_USER_START",
  AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS",
  AUTH_USER_ERROR: "AUTH_USER_ERROR",
  LOGOUT: "LOGOUT",
}